In [116]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [117]:
import pandas as pd

## DATA FRAME

In [118]:
df=pd.DataFrame([11,22,33],columns=["Name"])
df

   Name
0    11
1    22
2    33

In [119]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [120]:
data={
    'Name':["Anushka","Anusha","Avni"],
    'Age':[24,26,28],
    'Salary':[8,12,46]
}

In [121]:
df=pd.DataFrame(data)
print(data)

{'Name': ['Anushka', 'Anusha', 'Avni'], 'Age': [24, 26, 28], 'Salary': [8, 12, 46]}

## Data Frame Basics

In [122]:
df.head()

      Name  Age  Salary
0  Anushka   24       8
1   Anusha   26      12
2     Avni   28      46

In [123]:
df.tail()

      Name  Age  Salary
0  Anushka   24       8
1   Anusha   26      12
2     Avni   28      46

In [124]:
df.shape

(3, 3)

In [125]:
df.size

9

In [126]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [127]:
df=df.rename(columns={"Name":"NAME"})

In [128]:
df

      NAME  Age  Salary
0  Anushka   24       8
1   Anusha   26      12
2     Avni   28      46

In [129]:
df.rename(columns={"Salary":"Monthly Salary"},inplace=True)

In [130]:
df

      NAME  Age  Monthly Salary
0  Anushka   24               8
1   Anusha   26              12
2     Avni   28              46

In [131]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NAME            3 non-null      object
 1   Age             3 non-null      int64
 2   Monthly Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [132]:
df.describe()

        Age  Monthly Salary
count   3.0        3.000000
mean   26.0       22.000000
std     2.0       20.880613
min    24.0        8.000000
25%    25.0       10.000000
50%    26.0       12.000000
75%    27.0       29.000000
max    28.0       46.000000

In [133]:
df.to_csv("Dummy.csv")

In [134]:
df[["NAME"]]

      NAME
0  Anushka
1   Anusha
2     Avni

In [135]:
df[["NAME","Monthly Salary"]]

      NAME  Monthly Salary
0  Anushka               8
1   Anusha              12
2     Avni              46

In [136]:
df.loc[df["NAME"]== "Anushka"]

      NAME  Age  Monthly Salary
0  Anushka   24               8

In [137]:
df.iloc[1]

NAME              Anusha
Age                   26
Monthly Salary        12
Name: 1, dtype: object

In [138]:
df.iloc[0:2]

      NAME  Age  Monthly Salary
0  Anushka   24               8
1   Anusha   26              12

In [139]:
df.loc[0:2]

      NAME  Age  Monthly Salary
0  Anushka   24               8
1   Anusha   26              12
2     Avni   28              46

In [140]:
df['Age'] > 24

0    False
1     True
2     True
Name: Age, dtype: bool

In [141]:
df[(df['Age'] >= 25)]

     NAME  Age  Monthly Salary
1  Anusha   26              12
2    Avni   28              46

In [142]:
df.where(df['Age']>26)

   NAME   Age  Monthly Salary
0   NaN   NaN             NaN
1   NaN   NaN             NaN
2  Avni  28.0            46.0

## Add New Column

In [143]:
df['Team']=["IT",'HR','Model']

In [144]:
df

      NAME  Age  Monthly Salary   Team
0  Anushka   24               8     IT
1   Anusha   26              12     HR
2     Avni   28              46  Model

In [145]:
df.loc[len(df)]=['Ana',19,3,'Student']

In [146]:
df

      NAME  Age  Monthly Salary     Team
0  Anushka   24               8       IT
1   Anusha   26              12       HR
2     Avni   28              46    Model
3      Ana   19               3  Student

In [147]:
df.loc[0,"Monthly Salary"]=90

In [148]:
df

      NAME  Age  Monthly Salary     Team
0  Anushka   24              90       IT
1   Anusha   26              12       HR
2     Avni   28              46    Model
3      Ana   19               3  Student

In [149]:
df.drop(df[df.NAME=="Anushka"].index)

     NAME  Age  Monthly Salary     Team
1  Anusha   26              12       HR
2    Avni   28              46    Model
3     Ana   19               3  Student

In [150]:
df.drop("Team",axis=1)

      NAME  Age  Monthly Salary
0  Anushka   24              90
1   Anusha   26              12
2     Avni   28              46
3      Ana   19               3

In [151]:
df.sort_values(by="Monthly Salary")

      NAME  Age  Monthly Salary     Team
3      Ana   19               3  Student
1   Anusha   26              12       HR
2     Avni   28              46    Model
0  Anushka   24              90       IT

## DATE

In [152]:
df["DOJ"]=['2024-10-23','2019-11-23','2026-08-09','2022-12-3']

In [153]:
df

      NAME  Age  Monthly Salary     Team         DOJ
0  Anushka   24              90       IT  2024-10-23
1   Anusha   26              12       HR  2019-11-23
2     Avni   28              46    Model  2026-08-09
3      Ana   19               3  Student   2022-12-3

In [154]:
df['DOJ']=pd.to_datetime(df["DOJ"])

In [155]:
df

      NAME  Age  Monthly Salary     Team        DOJ
0  Anushka   24              90       IT 2024-10-23
1   Anusha   26              12       HR 2019-11-23
2     Avni   28              46    Model 2026-08-09
3      Ana   19               3  Student 2022-12-03

In [156]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [157]:
df['DOJ'].dt.year

0    2024
1    2019
2    2026
3    2022
Name: DOJ, dtype: int32

In [158]:
df["LWD"]=df["DOJ"]+pd.Timedelta(days=90)

In [159]:
df

      NAME  Age  Monthly Salary     Team        DOJ        LWD
0  Anushka   24              90       IT 2024-10-23 2025-01-21
1   Anusha   26              12       HR 2019-11-23 2020-02-21
2     Avni   28              46    Model 2026-08-09 2026-11-07
3      Ana   19               3  Student 2022-12-03 2023-03-03

## Aggregation and group by

In [160]:
df['Team'].value_counts()

Team
IT         1
HR         1
Model      1
Student    1
Name: count, dtype: int64

In [165]:
df.groupby('DOJ')["Monthly Salary"].sum()

DOJ
2019-11-23    12
2022-12-03     3
2024-10-23    90
2026-08-09    46
Name: Monthly Salary, dtype: int64